transition.__cancel = transition.cancel

function transition.cancel(param)
  if param == nil then
    print("WARNING: Transition cancelling all transitions")
    transition.__cancel()
  else
    transition.__cancel(param)
  end
end

function transition.isTransitioning(whatToTest)

  -- we use the targetType variable to establish how we iterate at the end of this method
  local targetType = nil
  local iterationTarget = nil

  -- transition object or display object
  if "table" == type(whatToTest) then
    -- if the ._instantiatedByTransLib field exists, then we have a transition object
    if whatToTest._instantiatedByTransLib then
      targetType = "transition"
      -- otherwise, we have a display object
    else
      targetType = "displayobject"
    end
    -- sequence name or tag
  elseif "string" == type(whatToTest) then
    targetType = "tag"
  end

  local lib = transition
  local transitionTable = lib._transitionTable
  iterationTarget = whatToTest

  -- if enterframe was run already, if we have any running tweens they won't be in the lib._transitionTable variable, but in lib._enterFrameTweens
  if #transitionTable == 0 then
    transitionTable = lib._enterFrameTweens
  end

  -- iterate the table
  for i,tween in ipairs(transitionTable) do
    -- only cancel if the tween was not generated by the composer library
    if targetType and not tween._generatedByComposer then
      if targetType == "tag" then
        if tween.tag == iterationTarget then
          return true
        end
      elseif targetType == "displayobject" then
        if tween._target == iterationTarget then
          return true
        end
      elseif targetType == "transition" then
        if tween == iterationTarget then
          return true
        end
      end
    end
  end
  return false
end